<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>PhotonBypass.OutSource</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\ServerBridge\ServerBridge.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="EmailTemplates\CertEmail.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="EmailTemplates\FinishServiceAlert.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="EmailTemplates\ResetPassword.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
