<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>PhotonBypass.FreeRadius</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="MySql.Data" Version="9.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MikrotikRadius\MikrotikRadius.csproj" />
		<ProjectReference Include="..\ServerBridge\ServerBridge.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

</Project>
