USE FastBypass;
GO

DROP VIEW IF EXISTS TotalPlanState;
DROP VIEW IF EXISTS PlanState;
DROP TABLE IF EXISTS TrafficData;
DROP TABLE IF EXISTS [Server];
DROP TABLE IF EXISTS History;
DROP TABLE IF EXISTS Renewal;
DROP TABLE IF EXISTS ResetPassword;
DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS Price;
DROP TABLE IF EXISTS Realm;