<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>PhotonBypass.Mikrotik.Radius</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ServerBridge\ServerBridge.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\Tik4net\tik4net.objects\tik4net.objects.csproj" />
	</ItemGroup>

</Project>
