<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>PhotonBypass.ServerBridge</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SSH.NET" Version="2025.0.0" />
		<PackageReference Include="Refit" Version="8.0.0" />
	</ItemGroup>

    <ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\Tik4net\tik4net.objects\tik4net.objects.csproj" />
    </ItemGroup>

</Project>
