USE FastBypass;
GO

IF OBJECT_ID('Price') IS NULL
CREATE TABLE Price (
	Id					INT IDENTITY	NOT NULL	CONSTRAINT PK_Price_Id PRIMARY KEY,
	State				TINYINT			NOT NULL	CONSTRAINT DF_Price_State DEFAULT 2,
	IsDefault			BIT				NOT NULL	CONSTRAINT DF_Price_IsDefault DEFAULT 1,
	Title				NVARCHAR(15)	NOT NULL,
	Caption				NVARCHAR(255)	NOT NULL,
	Description			NVARCHAR(255)	NOT NULL,
	CalculatorCode		VARCHAR(511)	NOT NULL,
	Created				DATETIME		NOT NULL	CONSTRAINT DF_Price_Created DEFAULT GETDATE(),
)
GO
