USE FastBypass;
GO

IF OBJECT_ID('ResetPassword') IS NULL
CREATE TABLE ResetPassword (
	Id					INT IDENTITY	NOT NULL	CONSTRAINT PK_ResetPassword_Id PRIMARY KEY,
	AccountId			INT				NOT NULL	CONSTRAINT FK_ResetPassword_AccountId FOREIGN KEY REFERENCES Account (Id)
													ON DELETE CASCADE,
	ExpireDate			DATETIME		NOT NULL,
	HashCode			VARCHAR(88)		NOT NULL,
	Created				DATETIME		NOT NULL	CONSTRAINT DF_ResetPassword_Created DEFAULT GETDATE(),
)
GO
